// In "production" mode, the application sends anonymous telemetry requests. See https://p-u.vercel.app/telemetry
export const ENV = "production";

// URL of the warp-cors proxy server opened at application startup
export const URL_FOR_BYPASS_CORS = "http://127.0.0.1:61337/";

// URL of the API server
export const API_URL = "https://p-u.vercel.app";

export const BUTTONS_HOST = {
    gofile : document.getElementById("button_gofile"),
    litterbox : document.getElementById("button_litterbox"),
    fileio : document.getElementById("button_fileio"),
    tmpfilesorg : document.getElementById("button_tmpfilesorg"),
    cvsh : document.getElementById("button_cvsh"),
    kitc : document.getElementById("button_kitc"), 
    oshi : document.getElementById("button_oshi"),
    filebin : document.getElementById("button_filebin"),
    bashupload : document.getElementById("button_bashupload"),
    curlby : document.getElementById("button_curlby"),
    x0at : document.getElementById("button_x0at"),
    tommoteam : document.getElementById("button_tommoteam"),
    tempfilesninja : document.getElementById("button_tempfilesninja"),
    pixeldrain : document.getElementById("button_pixeldrain"),
    _1cloudfile : document.getElementById("button_1cloudfile"),
    bowfile : document.getElementById("button_bowfile"),
    uploadify : document.getElementById("button_uploadify"),
    anontransfer : document.getElementById("button_anontransfer"),
    tempsh : document.getElementById("button_tempsh"),
    uguuse : document.getElementById("button_uguuse"),
    nopaste : document.getElementById("button_nopaste"),
    udrop : document.getElementById("button_udrop"),
    tempsend : document.getElementById("button_tempsend"),
    _1fichier : document.getElementById("button_1fichier"),
    turbobit : document.getElementById("button_turbobit"),
    hitfile : document.getElementById("button_hitfile"),
    fileupload : document.getElementById("button_fileupload"),
    hexupload : document.getElementById("button_hexupload"),
    mexash : document.getElementById("button_mexash"),
    rapidfileshare : document.getElementById("button_rapidfileshare"),
    sendnow : document.getElementById("button_sendnow"),
    filetmp : document.getElementById("button_filetmp"),
    usersdrive : document.getElementById("button_usersdrive"),
    downloadgg : document.getElementById("button_downloadgg"),
    krakenfiles : document.getElementById("button_krakenfiles"),
    clicknupload : document.getElementById("button_clicknupload"),
    uploadee : document.getElementById("button_uploadee"),
    ccuto : document.getElementById("button_ccuto"),
    filespacecom : document.getElementById("button_filespacecom"),
    gulfup : document.getElementById("button_gulfup"),
    cyberfile : document.getElementById("button_cyberfile"),
    freefr : document.getElementById("button_freefr"),
    depositfiles : document.getElementById("button_depositfiles"),
    tmpsend : document.getElementById("button_tmpsend"),
    ufile : document.getElementById("button_ufile"),
    dropdownload : document.getElementById("button_dropdownload"),
    filemoon : document.getElementById("button_filemoon"),
    catbox : document.getElementById("button_catbox"),
    sendvid : document.getElementById("button_sendvid"),
    upstore : document.getElementById("button_upstore"),
    ddownload : document.getElementById("button_ddownload"),
    mp4upload : document.getElementById("button_mp4upload"),
    netu : document.getElementById("button_netu"),
    dropgalaxy : document.getElementById("button_dropgalaxy"),
    nitroflare : document.getElementById("button_nitroflare"),
    vidoza : document.getElementById("button_vidoza"),
    katfile : document.getElementById("button_katfile"),
    rapidgator : document.getElementById("button_rapidgator"),
    fastupload : document.getElementById("button_fastupload"),
    imgbb : document.getElementById("button_imgbb"),
    buzzheavier : document.getElementById("button_buzzheavier"),
    doodstream : document.getElementById("button_doodstream"),
    streama2z : document.getElementById("button_streama2z"),
    streamwish : document.getElementById("button_streamwish"),
    streamruby : document.getElementById("button_streamruby"),
    voesx : document.getElementById("button_voesx"),
    devuploads : document.getElementById("button_devuploads"),
    mediacm : document.getElementById("button_mediacm"),
    dailyuploads : document.getElementById("button_dailyuploads"),
    uploady : document.getElementById("button_uploady"),
    dosyaco : document.getElementById("button_dosyaco"),
    dbreeme : document.getElementById("button_dbreeme"),
    douploads : document.getElementById("button_douploads"),
    uptomega : document.getElementById("button_uptomega"),
    vikingfile : document.getElementById("button_vikingfile"),
    fileditch : document.getElementById("button_fileditch"),
    s3kai : document.getElementById("button_s3kai"),
    m1rai : document.getElementById("button_m1rai"),
    lurkmoreuguu : document.getElementById("button_lurkmoreuguu"),
    uguu : document.getElementById("button_uguu"),
    rapidshareio : document.getElementById("button_rapidshareio"),
    filer : document.getElementById("button_filer"),
    dataupload : document.getElementById("button_dataupload"),
    uploadhive : document.getElementById("button_uploadhive"),
    kawaiisu : document.getElementById("button_kawaiisu"),
    quax : document.getElementById("button_quax"),
    end2end : document.getElementById("button_end2end"),
    up2share : document.getElementById("button_up2share"),
    atomauth : document.getElementById("button_atomauth"),
    darkibox : document.getElementById("button_darkibox"),
    desiupload : document.getElementById("button_desiupload"),
    gofileto : document.getElementById("button_gofileto"),
    ayayabeauty : document.getElementById("button_ayayabeauty"),
    filegram : document.getElementById("button_filegram"),
    goodstream : document.getElementById("button_goodstream"),
    dropload : document.getElementById("button_dropload"),
    gettsu : document.getElementById("button_gettsu"),
    oneupload : document.getElementById("button_oneupload"),
    earnvids : document.getElementById("button_earnvids"),
    vinovo : document.getElementById("button_vinovo"),
    uploadrar : document.getElementById("button_uploadrar"),
    vidguard : document.getElementById("button_vidguard"),
    savefiles : document.getElementById("button_savefiles"),
    filespayouts : document.getElementById("button_filespayouts"),
    fileaxa : document.getElementById("button_fileaxa"),
    nelion : document.getElementById("button_nelion"),
    uploadflix : document.getElementById("button_uploadflix"),
    filepv : document.getElementById("button_filepv"),
    filestore : document.getElementById("button_filestore"),
    dz4up : document.getElementById("button_dz4up"),
    wdfiles : document.getElementById("button_wdfiles"),
    xupin : document.getElementById("button_xupin"),
    fastdown : document.getElementById("button_fastdown"),
    f2h : document.getElementById("button_f2h"),
    nippyfile : document.getElementById("button_nippyfile"),
    uploadfilepl : document.getElementById("button_uploadfilepl"),
    mega4up : document.getElementById("button_mega4up"),
    hostuje : document.getElementById("button_hostuje"),
    supervideo : document.getElementById("button_supervideo"),
    mixloads : document.getElementById("button_mixloads"),
    up4stream : document.getElementById("button_up4stream"),
    uqload : document.getElementById("button_uqload"),
    lulustream : document.getElementById("button_lulustream"),
    upfiles : document.getElementById("button_upfiles"),
    streambolt : document.getElementById("button_streambolt"),
    megaup : document.getElementById("button_megaup"),
    _1filesharing : document.getElementById("button_1filesharing"),
    datavaults : document.getElementById("button_datavaults"),
    dropmb : document.getElementById("button_dropmb"),
    filemirage : document.getElementById("button_filemirage"),
    pomflainla : document.getElementById("button_pomflainla"),
    ranoz : document.getElementById("button_ranoz"),
    theusercloud : document.getElementById("button_theusercloud"),
    imgbank : document.getElementById("button_imgbank")
}

export const HOST_SITES = [
    { url: 'https://1fichier.com/', discriminator: '1fichier.com', name: "1fichier", api: "optional", anonymous_specs: ["300 GB", "15 days"], connected_specs: ["300 GB", "30 days"], bypass_check: false },
    { url: 'https://torbobit.net/?site_version=1&from_mirror=1', discriminator: 'torbobit.net', name: "Turbobit", api: "optional", anonymous_specs: ["200 MB", "7 days"], connected_specs: ["200 GB", "30 days"], bypass_check: false },
    { url: 'https://bowfile.com/', discriminator: 'bowfile.com', name: "Bowfile", api: "no", bypass_check: false },
    { url: 'https://gofile.io', discriminator: 'gofile.io', name: "Gofile", api: "optional", anonymous_specs: ["infinite", "10 days"], connected_specs: ["infinite", "10 days"], bypass_check: false },
    { url: 'https://hitfile.net/?site_version=1&from_mirror=1', discriminator: 'hitfile.net', name: "Hitfile", api: "optional", anonymous_specs: ["4 GB", "30 days"], connected_specs: ["100 GB", "30 days"], bypass_check: false },
    { url: 'https://1cloudfile.com/', discriminator: '1cloudfile.com', name: "1cloudfile", api: "no", bypass_check: false },
    { url: 'https://file-upload.org/', discriminator: 'file-upload.org', name: "file-upload.org", api: "no", bypass_check: false },
    { url: 'http://rapidfileshare.net/', discriminator: 'rapidfileshare.net', name: "RapidFileShare", api: "no", bypass_check: false },
    { url: 'https://www.upload.ee/', discriminator: 'upload.ee', name: "Upload.ee", api: "no", bypass_check: false },
    { url: 'https://netu.ac/', discriminator: 'waaw.ac', name: "Netu", api: "optional", anonymous_specs: ["8 GB", "30 days"], connected_specs: ["100 GB", "30 days"], bypass_check: false },
    { url: 'https://buzzheavier.com/', discriminator: 'buzzheavier.com', name: "Buzzheavier", api: "optional", anonymous_specs: ["infinite", "7 days"], connected_specs: ["infinite", "7 days"], bypass_check: false },
    { url: 'https://hexload.com/', discriminator: 'hexload.com', name: "HexUpload", api: "no", bypass_check: false },
    { url: 'https://vikingfile.com/', discriminator: 'vikingfile.com', name: "VikingFile", api: "no", bypass_check: false },
    { url: 'https://dailyuploads.net/', discriminator: 'dailyuploads.net', name: "DailyUploads", api: "no", bypass_check: true },
    { url: 'https://usersdrive.com/', discriminator: 'usersdrive.com', name: "UsersDrive", api: "no", bypass_check: false },
    { url: 'https://send.now/', discriminator: 'send.now', name: "Send.now", api: "no", bypass_check: false },
    { url: 'https://mexa.sh/', discriminator: 'mexa.sh', name: "Mexa.sh", api: "no", bypass_check: false },
    { url: 'https://uploadify.net/', discriminator: 'uploadify.net', name: "Uploadify", api: "no", bypass_check: false },
    { url: 'https://clicknupload.click/', discriminator: 'clicknupload.click', name: "Clicknupload", api: "no", bypass_check: false },
    { url: 'https://rachel.filespace.com/', discriminator: 'filespace.com', name: "Filespace", api: "no", bypass_check: false },
    { url: 'https://www.gulf-up.com/', discriminator: 'gulf-up.com', name: "Gulfup", api: "optional", anonymous_specs: ["200 MB", "10 days"], connected_specs: ["10 GB", "30 days"], bypass_check: false },
    { url: 'https://fastupload.io/', discriminator: 'fastupload.io', name: "Fastupload", api: "no", bypass_check: false },
    { url: 'https://uploadhive.com/', discriminator: 'uploadhive.com', name: "UploadHive", api: "no", bypass_check: false },
    { url: 'https://dfiles.eu/', discriminator: 'dfiles.eu', name: "DespoitFiles", api: "no", bypass_check: false },
    { url: 'https://download.gg/', discriminator: 'download.gg', name: "Download.gg", api: "no", bypass_check: false },
    { url: 'https://sendvid.com/', discriminator: 'sendvid.com', name: "Sendvid", api: "no", bypass_check: false },
    { url: 'https://uploady.io/', discriminator: 'uploady.io', name: "Uploady", api: "optional", anonymous_specs: ["1 GB", "30 days"], connected_specs: ["100 GB", "30 days"], bypass_check: false },
    { url: 'https://anontransfer.com/', discriminator: 'anontransfer.com', name: "AnonTransfer", api: "no", bypass_check: false },
    { url: 'https://litterbox.catbox.moe/', discriminator: 'litter.catbox.moe', name: "Litterbox", api: "no", bypass_check: false },
    { url: 'https://temp.sh/', discriminator: 'temp.sh', name: "Temp.sh", api: "no", bypass_check: false },
    { url: 'https://tmpfiles.org/', discriminator: 'tmpfiles.org', name: "TmpFiles.org", api: "no", bypass_check: false },
    { url: 'https://gofile.to/', discriminator: 'gofile.to', name: "Gofile.to", api: "no", bypass_check: false },
    { url: 'https://transfert.free.fr/', discriminator: 'free.fr', name: "Free.fr", api: "no", bypass_check: false },
    { url: 'https://uguu.se/', discriminator: 'uguu.se', name: "Uguu.se", api: "no", bypass_check: false },
    { url: 'https://upload.lurkmore.com/', discriminator: 'lurkmore.com', name: "lurkmore Uguu", api: "no", bypass_check: false },
    { url: 'https://uguu.aishiteiru.moe/', discriminator: 'aishiteiru.moe', name: "Uguu", api: "no", bypass_check: false },
    { url: 'https://filer.net/', discriminator: 'filer.net', name: "Filer.net", api: "no", bypass_check: false },
    { url: 'https://filebin.net/', discriminator: 'filebin.net', name: "Filebin", api: "no", bypass_check: false },
    { url: 'https://douploads.net/', discriminator: 'douploads.net', name: "DoUploads", api: "no", bypass_check: false },
    { url: 'https://dataupload.net/', discriminator: 'dataupload.net', name: "Dataupload", api: "no", bypass_check: false },
    { url: 'https://upstore.net/', discriminator: 'upstore.net', name: "Upstore", api: "no", bypass_check: false },
    { url: 'https://ufile.io/', discriminator: 'ufile.io', name: "uFile", api: "no", bypass_check: false },
    { url: 'https://krakenfiles.com/', discriminator: 'krakenfiles.com', name: "Krakenfiles", api: "optional", anonymous_specs: ["1 GB", "30 days"], connected_specs: ["5 GB", "90 days"], bypass_check: false },
    { url: 'https://rapidshare.io/', discriminator: 'rapidshare.io', name: "Rapidshare.io", api: "no", bypass_check: false },
    { url: 'https://media.cm/', discriminator: 'media.cm', name: "Media.cm", api: "no", bypass_check: false },
    { url: 'https://oshi.at/', discriminator: 'oshi.at', name: "Oshi.at", api: "no", bypass_check: false },
    { url: 'https://bashupload.com/', discriminator: 'bashupload.com', name: "bashupload", api: "no", bypass_check: false },
    { url: 'https://tommo.team/', discriminator: 'tommo.team', name: "Tommo.team", api: "no", bypass_check: false },
    { url: 'https://desiupload.co/', discriminator: 'desiupload.co', name: "DesiUpload", api: "no", bypass_check: false },
    { url: 'https://tempfiles.ninja/', discriminator: 'tempfiles.ninja', name: "tempfiles.ninja", api: "no", bypass_check: false },
    { url: 'https://fileditch.com/', discriminator: 'fileditchfiles.me', name: "Fileditch", api: "no", bypass_check: false },
    { url: 'https://up2sha.re/', discriminator: 'up2sha.re', name: "Up2Share", api: "optional", anonymous_specs: ["64 MB", "30 days"], connected_specs: ["1 GB", "30 days"], bypass_check: false },
    { url: 'https://dbree.org/', discriminator: 'dbree.org', name: "Dbree", api: "no", bypass_check: false },
    { url: 'https://www.udrop.com/', discriminator: 'udrop.com', name: "Udrop", api: "no", bypass_check: false },
    { url: 'https://tempsend.com/', discriminator: 'tempsend.com', name: "Tempsend", api: "no", bypass_check: false },
    { url: 'https://www.curl.by/', discriminator: 'curl.by', name: "Curl.by", api: "no", bypass_check: false },
    { url: 'https://uptomega.net/', discriminator: 'uptomega.net', name: "Uptomega", api: "no", bypass_check: false },
    { url: 'https://qu.ax/', discriminator: 'qu.ax', name: "qu.ax", api: "no", bypass_check: false },
    { url: 'https://filetmp.com/', discriminator: 'filetmp.com', name: "FileTmp", api: "no", bypass_check: false },
    { url: 'https://ccu.to/', discriminator: 'ccu.to', name: "CCU.to", api: "no", bypass_check: false },
    { url: 'https://dosya.co/', discriminator: 'dosya.co', name: "Dosya.co", api: "no", bypass_check: false },
    { url: 'https://imgbb.com/', discriminator: 'ibb.co', name: "ImgBB", api: "no", bypass_check: false },
    { url: 'https://ki.tc/', discriminator: 'ki.tc', name: "ki.tc", api: "no", bypass_check: false },
    { url: 'https://uploadfile.pl/', discriminator: 'uploadfile.pl', name: "UploadFile.pl", api: "no", bypass_check: false },
    { url: 'https://nippyfile.com/', discriminator: 'nippyfile.com', name: "NippyFile", api: "no", bypass_check: false },
    { url: 'https://filestore.to/', discriminator: 'filestore.to', name: "Filestore", api: "no", bypass_check: false },
    { url: 'https://down.fast-down.com/', discriminator: 'fast-down.com', name: "Fast Down", api: "no", bypass_check: false },
    { url: 'https://cyberfile.me/', discriminator: 'cyberfile.me', name: "Cyberfile", api: "no", bypass_check: false },
    { url: 'https://end2end.tech/', discriminator: 'end2end.tech', name: "end2end", api: "no", bypass_check: true },
    { url: 'https://c-v.sh/', discriminator: 'c-v.sh', name: "c-v.sh", api: "no", bypass_check: false },
    { url: 'https://x0.at/', discriminator: 'x0.at', name: "x0.at", api: "no", bypass_check: false },
    { url: 'https://nopaste.net/', discriminator: 'nopaste.net', name: "Nopaste", api: "no", bypass_check: false },
    { url: 'https://tmpsend.com/', discriminator: 'tmpsend.com', name: "TmpSend", api: "no", bypass_check: false },
    { url: 'https://mega4upload.net/', discriminator: 'mega4upload.net', name: "Mega4up", api: "no", bypass_check: false },
    { url: 'https://hostuje.net/', discriminator: 'hostuje.net', name: "Hostuje", api: "no", bypass_check: false },
    { url: 'https://uploadflix.cc/', discriminator: 'uploadflix.com', name: "UploadFlix", api: "no", bypass_check: false },
    { url: 'https://dz4up.com/', discriminator: 'dz4up.com', name: "DZ4Up", api: "no", bypass_check: false },
    { url: 'https://wdfiles.ru/', discriminator: 'wdfiles.ru', name: "WDFiles", api: "no", bypass_check: false },
    { url: 'https://up.m1r.ai/', discriminator: 'm1r.ai', name: "m1r.ai", api: "no", bypass_check: false },
    { url: 'https://up.s3k.ai/', discriminator: 's3k.ai', name: "s3k.ai", api: "no", bypass_check: false },
    { url: 'https://www.xup.in/', discriminator: 'xup.in', name: "XUP", api: "no", bypass_check: false },
    { url: 'https://filepv.com/', discriminator: 'filepv.com', name: "Filepv", api: "no", bypass_check: false },
    { url: 'https://f2h.io/', discriminator: 'f2h.io', name: "F2H", api: "no", bypass_check: false },
    { url: 'https://ayaya.beauty/', discriminator: 'ayaya.beauty', name: "ayaya.beauty", api: "no", bypass_check: false },
    { url: 'https://nelion.me/', discriminator: 'nelion.me', name: "Nelion", api: "no", bypass_check: false },
    { url: 'https://atomauth.com/', discriminator: 'atomauth.com', name: "Atomauth", api: "no", bypass_check: false },
    { url: 'https://imouto.kawaii.su/', discriminator: 'kawaii.su', name: "imouto.kawaii.su", api: "no", bypass_check: false },
    { url: 'https://doodstream.com/', discriminator: 'do7go.com', name: "DoodStream", api: "required", bypass_check: false },
    { url: 'https://pixeldrain.com/', discriminator: 'pixeldrain.com', name: "Pixeldrain", api: "required", bypass_check: false },
    { url: 'https://drop.download/', discriminator: 'drop.download', name: "Drop.download", api: "required", bypass_check: false },
    { url: 'https://filemoon.sx/', discriminator: 'filemoon.sx', name: "FileMoon", api: "required", bypass_check: false },
    { url: 'https://catbox.moe/', discriminator: 'files.catbox.moe', name: "Catbox", api: "required", bypass_check: false },
    { url: 'https://ddownload.com/', discriminator: 'ddownload.com', name: "ddownload", api: "required", bypass_check: false },
    { url: 'https://mp4upload.com/', discriminator: 'mp4upload.com', name: "mp4upload", api: "required", bypass_check: false },
    { url: 'https://dropgalaxy.com/', discriminator: 'dgdrive.site', name: "DropGalaxy", api: "required", bypass_check: false },
    { url: 'https://nitroflare.com/', discriminator: 'nitroflare.com', name: "Nitroflare", api: "required", bypass_check: false },
    { url: 'https://vidoza.net/', discriminator: 'vidoza.net', name: "Vidoza", api: "required", bypass_check: false },
    { url: 'https://katfile.com/', discriminator: 'katfile.com', name: "Katfile", api: "required", bypass_check: false },
    { url: 'https://rapidgator.net/', discriminator: 'rapidgator.net', name: "Rapidgator", api: "required", bypass_check: false },
    { url: 'https://streama2z.com/', discriminator: 'streama2z.xyz', name: "StreamA2Z", api: "required", bypass_check: false },
    { url: 'https://streamwish.com/', discriminator: 'strwish.com', name: "StreamWish", api: "required", bypass_check: false },
    { url: 'https://streamruby.com/', discriminator: 'rubystm.com', name: "StreamRuby", api: "required", bypass_check: false },
    { url: 'https://voe.sx/', discriminator: 'voe.sx', name: "Voe.sx", api: "required", bypass_check: false },
    { url: 'https://devuploads.com/', discriminator: 'devuploads.com', name: "DevUploads", api: "required", bypass_check: false },
    { url: 'https://darkibox.com/', discriminator: 'darkibox.com', name: "Darkibox", api: "required", bypass_check: false },
    { url: 'https://filegram.to/', discriminator: 'filegram.to', name: "Filegram", api: "required", bypass_check: false },
    { url: 'https://goodstream.one/', discriminator: 'goodstream.one', name: "Goodstream", api: "required", bypass_check: false },
    { url: 'https://dropload.io/', discriminator: 'dropload.io', name: "Dropload", api: "required", bypass_check: false },
    { url: 'https://gett.su/', discriminator: 'gett.su', name: "GeTT", api: "required", bypass_check: false },
    { url: 'https://oneupload.to/', discriminator: 'oneupload.to', name: "OneUpload", api: "required", bypass_check: false },
    { url: 'https://earnvids.com/', discriminator: 'smoothpre.com', name: "EarnVids", api: "required", bypass_check: false },
    { url: 'https://vinovo.si/', discriminator: 'vinovo.to', name: "Vinovo", api: "required", bypass_check: false },
    { url: 'https://uploadrar.com/', discriminator: 'uploadrar.com', name: "Uploadrar", api: "required", bypass_check: false },
    { url: 'https://vidguard.to/', discriminator: 'listeamed.net', name: "Vidguard", api: "required", bypass_check: false },
    { url: 'https://savefiles.com/', discriminator: 'savefiles.com', name: "SaveFiles", api: "required", bypass_check: false },
    { url: 'https://filespayouts.com/', discriminator: 'filespayouts.com', name: "Filespayouts", api: "required", bypass_check: false },
    { url: 'https://fileaxa.com/', discriminator: 'fileaxa.com', name: "Fileaxa", api: "required", bypass_check: false },
    { url: 'https://supervideo.cc/', discriminator: 'supervideo.cc', name: "SuperVideo", api: "required", bypass_check: false },
    { url: 'https://mixloads.to/', discriminator: 'mixloads.to', name: "MixLoads", api: "required", bypass_check: false },
    { url: 'https://up4stream.com/', discriminator: 'ups2up.fun', name: "Up4Stream", api: "required", bypass_check: false },
    { url: 'https://uqload.cx/', discriminator: 'uqload.cx', name: "Uqload", api: "required", bypass_check: false },
    { url: 'https://lulustream.com/', discriminator: 'lulustream.com', name: "LuluStream", api: "required", bypass_check: false },
    { url: 'https://upfiles.com/', discriminator: 'upfiles.com', name: "UpFiles", api: "required", bypass_check: false },
    { url: 'https://streambolt.tv/', discriminator: 'streambolt.tv', name: "StreamBolt", api: "required", bypass_check: false },
    { url: 'https://megaup.net/', discriminator: 'megaup.net', name: "MegaUp", api: "no", bypass_check: false },
    { url: 'https://1filesharing.com/', discriminator: '1filesharing.com', name: "1filesharing", api: "no", bypass_check: false },
    { url: 'https://datavaults.co/', discriminator: 'datavaults.co', name: "Data Vaults", api: "no", bypass_check: false },
    { url: 'https://dropmb.com/', discriminator: 'dropmb.com', name: "DropMB", api: "no", bypass_check: false },
    { url: 'https://filemirage.com/', discriminator: 'filemirage.com', name: "FileMirage", api: "optional", anonymous_specs: ["50 GB", "30 days"], connected_specs: ["50 GB", "30 days"], bypass_check: false },
    { url: 'https://pomf.lain.la/', discriminator: 'lain.la', name: "Pomf.lain.la", api: "no", bypass_check: false },
    { url: 'https://ranoz.gg/', discriminator: 'ranoz.gg', name: "Ranoz", api: "no", bypass_check: false },
    { url: 'https://theuser.cloud/', discriminator: 'theuser.cloud', name: "Theuser.cloud", api: "no", bypass_check: false },
    { url: 'https://imgbank.cz/', discriminator: 'imgbank.cz', name: "IMG Bank", api: "no", bypass_check: false }
]

export const BUTTONS = {
    toggle_upload_mode : document.getElementById("toggle_upload_mode"),
    multiple_host_popup : document.getElementById("button_multiple_host_popup"),
    upload_generic : document.querySelectorAll('[value="upload_button"]'),
    select_box_container : document.querySelectorAll('[id="select_box_container"]'),
    save_selected_host : document.getElementById("button_save_selected_host"),
    cancel_selected_host : document.getElementById("button_cancel_selected_host"),
    upload_profile : document.getElementById("button_upload_profile"),
    popup_new_profile : document.getElementById("popup_new_profile_button"),
    select_host : document.getElementById("select_host_button"),
    delete_profiles : document.getElementById("delete_profiles_button"),
    rename_profiles : document.getElementById("rename_profiles_button"),
    close : document.getElementById("close_button"),
    minimize : document.getElementById("minimize_button"),
    maximize : document.getElementById("maximize_button"),
    popup_browse : document.getElementById("popup_browse_button"),
    popup_upload_local : document.getElementById("popup_upload_button_local"),
    popup_upload_url : document.getElementById("popup_upload_button_url"),
    copy : document.getElementById("copy_button"),
    delete_file_input : document.getElementById("delete_file_input_button"),
    set_api_key : document.getElementById("set_api_key_button"),
    upload_local_file : document.getElementById("upload_local_file_button"),
    upload_from_url : document.getElementById("upload_from_url_button"),
    upload_history : document.getElementById("upload_history_button"),
    clear_history : document.getElementById("clear_history_button"),
    check_status : document.getElementById("check_status_button"),
    manage_api_keys : document.getElementById("manage_api_keys_button"),
    import_popup : document.getElementById("import_button_popup"),
    export_popup : document.getElementById("export_button_popup"),
    import : document.getElementById("import_button"),
    export : document.getElementById("export_button"),
    close_popup : document.querySelectorAll('[id="close_popup_button"]'),
    delete_search_input : document.getElementById("delete_search_input"),
    about : document.getElementById("about_button"),
    scroll_top : document.getElementById("scroll_top_button"),
    settings : document.getElementById("settings_button"),
    delete_all_deletable : document.getElementById("delete_all_deletable_button"),
    toggle_api_keys_required : document.getElementById("toggle_api_keys_required"),
    toggle_api_keys_optional : document.getElementById("toggle_api_keys_optional"),
    start_tour : document.getElementById("start_tour_button"),
    ignore_onboarding : document.getElementById("ignore_onboarding_button"),
    review_onboarding : document.getElementById("review_onboarding_button")
}

export const SELECTS = {
    select_box : document.querySelectorAll('[id="select_box"]'),
    profile : document.getElementById("profile_select"),
    profile_menu : document.getElementById("profile_selector"),
    select_box_shell : document.getElementById("select_box_shell"),
    select_box_unstable : document.getElementById("select_box_unstable"),
    select_box_popups : document.getElementById("select_box_popups"),
    select_box_deleted_links : document.getElementById("select_box_deleted_links")
}

const table_of_providers = document.querySelector('[value="host"]');
const tbody_of_providers = table_of_providers.querySelector("tbody");
const rows_of_providers = Array.from(tbody_of_providers.querySelectorAll("tr"));

export const ELEMENT_DISPLAYS = {
    upload_name : document.getElementById("upload_name"),
    new_version : document.getElementById("new_version_text"),
    current_version : document.getElementById("current_version_text"),
    filename_url_info : document.getElementById("filename_url_info"),
    final_upload_url : document.getElementById("final_upload_url"),
    set_api_key : document.getElementById("set_api_key"),
    local_upload_file : document.getElementById("local_upload_file"),
    url_upload_file : document.getElementById("url_upload_file"),
    conditions_of_use_link : document.getElementById("conditions_of_use_link"),
    tbody_of_providers,
    rows_of_providers,
    history_table_body : document.getElementById("history_table_body"),
    stats_text : document.getElementById("stats_text"),
    manage_api_keys_body : document.getElementById("manage_api_keys_body"),
    search_icon : document.getElementById("search_icon"),
    info_text : document.getElementById("info_text"),
    add_to_context_menu : document.getElementById("add_to_context_menu_text"),
    polyuploader_version_text : document.getElementById("polyuploader_version_text"),
    scroll_top_button_container : document.getElementById("scroll_top_button_container"),
    conditions_of_use : document.getElementById("conditions_of_use"),
    unstable_hosts_text : document.getElementById("unstable_hosts_text"),
    last_blur : document.getElementById("last_blur"),
    import_export_container : document.getElementById("import_export_container"),
    deleted_files_text : document.getElementById("deleted_files_text"),
    hide_show_api_keys_text : document.getElementById("hide_show_api_keys_text"),
    api_keys_required_menu : document.getElementById("api_keys_required_menu"),
    required_api_keys_table : document.getElementById("required_api_keys_table"),
    api_keys_table : document.getElementById("api_keys_table"),
    no_api_keys_text : document.getElementById("no_api_keys_text"),
    api_keys_optional_menu : document.getElementById("api_keys_optional_menu"),
    optional_api_keys_table : document.getElementById("optional_api_keys_table"),
    connected_info_text : document.getElementById("connected_info_text")
}

export const POPUPS = {
    profile_maker : document.getElementById("profile_maker_popup"),
    update : document.getElementById("update_popup"),
    new_version_download : document.getElementById("popup_new_version_download"),
    upload : document.getElementById("upload_popup"),
    upload_container : document.getElementById("popup_container"),
    drag_file_withtout_host : document.getElementById("drag_file_withtout_host"),
    uploaded_files_history : document.getElementById("uploaded_files_history_popup"),
    manage_api_keys : document.getElementById("manage_api_keys_popup"),
    import : document.getElementById("import_popup"),
    export : document.getElementById("export_popup"),
    info : document.getElementById("info_popup"),
    about : document.getElementById("about_popup"),
    settings : document.getElementById("settings_popup"),
    welcome : document.getElementById("welcome_popup")
}

export const INPUTS = {
    profile_name : document.getElementById("profile_name"),
    popup_file : document.getElementById("popup_file_input"),
    url_upload : document.getElementById("url_upload_input"),
    api_key : document.getElementById("api_key_input")
}

export const STATE = {
    sort_states : [null, null, null],
    host : "",
    is_drag_file : false,
    is_dragging_over : false,
    file_to_upload: "",
    file_to_upload_name: "",
    file_to_upload_size: "",
    last_clicked_button: null,
    link_receive : 0,
    force_keep_file : 0,
    set_api_key_popup : false,
    button_upload_status : 0,
    drag_file : null,
    drag_file_name : null,
    drag_file_size : null,
    profile_status : 0,
    selected_profile : "",
    upload_mode : "local",
    window_status : "minimize",
    original_order : Array.from(ELEMENT_DISPLAYS.rows_of_providers),
    controller: new AbortController(),
    get signal() {
        return this.controller.signal;
    }
}